In [1]:
import pandas as pd 
import numpy as np

In [2]:
import os

In [3]:
os.chdir('C:\\New folder (2)')

In [4]:
data=pd.read_csv("quikr_car.csv")

In [5]:
data.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [6]:
data.tail()

,name,company,year,Price,kms_driven,fuel_type
793,Ta,Tara,zest,"3,10,000",NaN,NaN
794,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
795,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
796,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
797,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 798 entries, 0 to 797
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        798 non-null    object
 1   company     798 non-null    object
 2   year        798 non-null    object
 3   Price       798 non-null    object
 4   kms_driven  748 non-null    object
 5   fuel_type   745 non-null    object
dtypes: object(6)
memory usage: 37.5+ KB

In [8]:
data.describe(include='all')

              name company  year          Price  kms_driven fuel_type
count          798     798   798            798         748       745
unique         525      48    61            274         258         3
top     Honda City  Maruti  2015  Ask For Price  45,000 kms    Petrol
freq            11     216    93             33          28       402

In [9]:
data.isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    50
fuel_type     53
dtype: int64

solve the null value

In [10]:
data.isnull().sum().sum()

np.int64(103)

In [11]:
data2 = data.fillna(value = 0)
data2

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
793,Ta,Tara,zest,"3,10,000",0,0
794,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
795,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
796,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,0
797,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,0

In [12]:
data2.isnull().sum().sum()

np.int64(0)

In [13]:
data2.isnull().sum()

name          0
company       0
year          0
Price         0
kms_driven    0
fuel_type     0
dtype: int64

In [14]:
data.columns = data.columns.str.lower()
data.columns = data.columns.str.replace(' ','_')

In [15]:
data.columns

Index(['name', 'company', 'year', 'price', 'kms_driven', 'fuel_type'], dtype='object')

In [17]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\users\user\downloads\new folder\anaconda\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\user\downloads\new folder\anaconda\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\downloads\new folder\anaconda\lib\site-packages (from sqlalchemy) (4.12.2)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 917.4 kB/s eta 0:00:03
   ------- -------------------------------- 0.5/2.8 MB 917.4 kB/s eta 0:00:03
   ----------- ---------------------------- 0.8/2.8 MB 784.1 kB/s eta 0:00:03
   ----------- ---------------------------- 0.8/2.8 MB 784.1 kB/s eta 0:00:03
   --------------- ------------------------ 1.0/2.8 MB 766.1 kB/s eta 0:00:03
   --------------- ------------------------ 1.0/2.8 MB 766.1 kB/s eta 0:00:03
   ------------------- -------------------- 1.3/2.8 MB 702.0 kB/s eta 0:00:03
   ------------------- -------------------- 1.3/2.8 MB 702.0 kB/s eta 0:00:03
   ---------------------- ----------------- 1.6/2.8 MB 700.8 kB/s eta 0:00:02
   ---------------------- ----------------- 1.6/2.8 MB 700.8 kB/s eta 0:00:02
   ---------------------- ----------------- 1.6/2.8 MB 700.8 kB/s eta 0:00:02
   ---------------------- ----------------- 1.6/2.8 MB 700.8 kB/s eta 0:00:02
   -------------------------- ------------- 1.8/2.8 MB 595.2 kB/s eta 0:00:02
   ------------------------------ --------- 2.1/2.8 MB 615.7 kB/s eta 0:00:02
   ------------------------------ --------- 2.1/2.8 MB 615.7 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.8 MB 621.5 kB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.8 MB 621.5 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.8 MB 628.6 kB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 640.3 kB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [18]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\user\downloads\new folder\anaconda\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\user\downloads\new folder\anaconda\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\user\downloads\new folder\anaconda\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\downloads\new folder\anaconda\lib\site-packages (from sqlalchemy) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

In [22]:
from sqlalchemy import create_engine
username = "postgres"
password = "1845"
host = "localhost"
port = "5432"
database = "customer_behaviours"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "customer"
data.to_sql(table_name, engine, if_exists="replace", index=False)

print("data successfully loaded into table '{table_name}' in database '{database}'.")

data successfully loaded into table '{table_name}' in database '{database}'.